server:
  port: 8088

spring:
  thymeleaf:
    cache: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  services:
    order-service: ${ORDER_SERVICE_URL:http://order-service:1085}
    invitation-service: ${INVITATION_SERVICE_URL:http://invitation-service:1084}
    template-service: ${TEMPLATE_SERVICE_URL:http://template-service:1083}
    auth-service: ${AUTH_SERVICE_URL:http://auth-service:1081}
    notification-service: ${NOTIFICATION_SERVICE_URL:http://notification-service:1087}

spring:
  flyway:
    default-schema: admin
    schemas: admin
    create-schemas: true
  jpa:
    properties:
      hibernate:
        default_schema: admin
