server:
  port: 8084

spring:
  cache:
    type: redis
    redis:
      time-to-live: 300000
  flyway:
    default-schema: invitation
    schemas: invitation
    create-schemas: true
  jpa:
    properties:
      hibernate:
        default_schema: invitation

app:
  rabbitmq:
    orders-exchange: baundang.orders
    rsvp-exchange: baundang.rsvp
    invitations-exchange: baundang.invitations
  base-url: ${APP_BASE_URL:https://baundang.id}
  midtrans:
    client-key: ${MIDTRANS_CLIENT_KEY}
    snap-js-url: ${MIDTRANS_SNAP_JS_URL:https://app.sandbox.midtrans.com/snap/snap.js}
