server:
  port: 8085

app:
  rabbitmq:
    exchange: baundang.orders
    routing-key:
      created: order.created
      paid: order.paid
      revised: order.revised
      revision-completed: revision.completed

spring:
  flyway:
    default-schema: orders
    schemas: orders
    create-schemas: true
  jpa:
    properties:
      hibernate:
        default_schema: orders
