server:
  port: 1086

app:
  midtrans:
    server-key: ${MIDTRANS_SERVER_KEY}
    is-production: ${MIDTRANS_IS_PRODUCTION:false}
  rabbitmq:
    orders-exchange: baundang.orders
    routing-key:
      paid: order.paid
      payment-failed: order.payment_failed
      gift-paid: gift.paid

spring:
  flyway:
    default-schema: payment
    schemas: payment
    create-schemas: true
  jpa:
    properties:
      hibernate:
        default_schema: payment

logging:
  level:
    id.baundang.common.logging.ServiceLoggingAspect: DEBUG
